import Foundation

enum ImageNetLabelLocalizer {
    static func localizedLabel(for identifier: String) -> String {
        let normalized = identifier
            .lowercased()
            .replacingOccurrences(of: "_", with: " ")

        let parts = normalized
            .split(separator: ",")
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }

        for phrase in parts {
            if let exact = exactLabels[phrase] {
                return exact
            }
        }

        for (keyword, translation) in keywordLabels where normalized.contains(keyword) {
            return translation
        }

        return parts.first.map { String($0) } ?? identifier
    }

    private static let exactLabels: [String: String] = [
        "tench": "丁桂鱼",
        "goldfish": "金鱼",
        "great white shark": "大白鲨",
        "tiger shark": "虎鲨",
        "hammerhead": "锤头鲨",
        "stingray": "黄貂鱼",
        "cock": "公鸡",
        "hen": "母鸡",
        "ostrich": "鸵鸟",
        "goldfinch": "金翅雀",
        "robin": "知更鸟",
        "magpie": "喜鹊",
        "bald eagle": "白头海雕",
        "vulture": "秃鹫",
        "great grey owl": "灰林鸮",
        "axolotl": "美西螈",
        "bullfrog": "牛蛙",
        "loggerhead": "红海龟",
        "box turtle": "箱龟",
        "common iguana": "绿鬣蜥",
        "komodo dragon": "科莫多巨蜥",
        "american alligator": "美洲短吻鳄",
        "triceratops": "三角龙",
        "king snake": "王蛇",
        "garter snake": "束带蛇",
        "green mamba": "绿曼巴蛇",
        "spider monkey": "蜘蛛猴",
        "gorilla": "大猩猩",
        "chimpanzee": "黑猩猩",
        "koala": "考拉",
        "wombat": "袋熊",
        "jellyfish": "水母",
        "starfish": "海星",
        "sea urchin": "海胆",
        "ladybug": "瓢虫",
        "bee": "蜜蜂",
        "ant": "蚂蚁",
        "grasshopper": "蚱蜢",
        "dragonfly": "蜻蜓",
        "cockroach": "蟑螂",
        "flamingo": "火烈鸟",
        "pelican": "鹈鹕",
        "penguin": "企鹅",
        "zebra": "斑马",
        "pig": "猪",
        "hippopotamus": "河马",
        "ox": "牛",
        "bison": "野牛",
        "ram": "公羊",
        "gazelle": "瞪羚",
        "llama": "羊驼",
        "skunk": "臭鼬",
        "badger": "獾",
        "armadillo": "犰狳",
        "sloth bear": "懒熊",
        "mongoose": "猫鼬",
        "meerkat": "狐獴",
        "tiger": "老虎",
        "lion": "狮子",
        "cheetah": "猎豹",
        "brown bear": "棕熊",
        "panda": "熊猫",
        "tabby": "猫",
        "tiger cat": "虎斑猫",
        "persian cat": "波斯猫",
        "siamese cat": "暹罗猫",
        "egyptian cat": "埃及猫",
        "lynx": "猞猁",
        "leopard": "豹",
        "snow leopard": "雪豹",
        "jaguar": "美洲豹",
        "grey fox": "灰狐",
        "red fox": "赤狐",
        "kit fox": "狐",
        "arctic fox": "北极狐",
        "wolf": "狼",
        "coyote": "郊狼",
        "hyena": "鬣狗",
        "red panda": "小熊猫",
        "espresso": "浓缩咖啡",
        "pizza": "披萨",
        "cheeseburger": "芝士汉堡",
        "hotdog": "热狗",
        "ice cream": "冰淇淋",
        "bagel": "贝果",
        "pretzel": "椒盐卷饼",
        "guacamole": "鳄梨酱",
        "banana": "香蕉",
        "orange": "橙子",
        "lemon": "柠檬",
        "pineapple": "菠萝",
        "pomegranate": "石榴",
        "strawberry": "草莓",
        "bell pepper": "甜椒",
        "cucumber": "黄瓜",
        "artichoke": "洋蓟",
        "mushroom": "蘑菇",
        "toilet tissue": "卫生纸"
    ]

    private static let keywordLabels: [(String, String)] = [
        ("retriever", "寻回犬"),
        ("terrier", "梗犬"),
        ("spaniel", "西班牙猎犬"),
        ("poodle", "贵宾犬"),
        ("shepherd", "牧羊犬"),
        ("hound", "猎犬"),
        ("mastiff", "獒犬"),
        ("husky", "哈士奇"),
        ("malamute", "雪橇犬"),
        ("chihuahua", "吉娃娃"),
        ("dalmatian", "斑点狗"),
        ("boxer", "拳师犬"),
        ("bulldog", "斗牛犬"),
        ("dog", "狗"),
        ("cat", "猫"),
        ("bird", "鸟"),
        ("shark", "鲨鱼"),
        ("fish", "鱼"),
        ("frog", "青蛙"),
        ("snake", "蛇"),
        ("turtle", "龟"),
        ("lizard", "蜥蜴"),
        ("crocodile", "鳄鱼"),
        ("alligator", "短吻鳄"),
        ("monkey", "猴子"),
        ("ape", "猿"),
        ("bear", "熊"),
        ("fox", "狐狸"),
        ("squirrel", "松鼠"),
        ("rabbit", "兔子"),
        ("hamster", "仓鼠"),
        ("mouse", "老鼠"),
        ("horse", "马"),
        ("deer", "鹿"),
        ("elephant", "大象"),
        ("rhinoceros", "犀牛"),
        ("camel", "骆驼"),
        ("otter", "水獭"),
        ("seal", "海豹"),
        ("whale", "鲸鱼"),
        ("dolphin", "海豚"),
        ("butterfly", "蝴蝶"),
        ("moth", "蛾"),
        ("beetle", "甲虫"),
        ("spider", "蜘蛛"),
        ("crab", "螃蟹"),
        ("lobster", "龙虾"),
        ("snail", "蜗牛"),
        ("slug", "蛞蝓"),
        ("car", "汽车"),
        ("truck", "卡车"),
        ("bus", "公交车"),
        ("train", "火车"),
        ("bicycle", "自行车"),
        ("motorcycle", "摩托车"),
        ("airliner", "客机"),
        ("airship", "飞艇"),
        ("boat", "船"),
        ("ship", "船"),
        ("scooter", "滑板车"),
        ("laptop", "笔记本电脑"),
        ("keyboard", "键盘"),
        ("mouse", "鼠标"),
        ("monitor", "显示器"),
        ("screen", "屏幕"),
        ("phone", "手机"),
        ("camera", "相机"),
        ("printer", "打印机"),
        ("remote control", "遥控器"),
        ("television", "电视"),
        ("microwave", "微波炉"),
        ("oven", "烤箱"),
        ("refrigerator", "冰箱"),
        ("washer", "洗衣机"),
        ("dishwasher", "洗碗机"),
        ("vacuum", "吸尘器"),
        ("lamp", "灯"),
        ("clock", "时钟"),
        ("chair", "椅子"),
        ("sofa", "沙发"),
        ("table", "桌子"),
        ("desk", "书桌"),
        ("bed", "床"),
        ("pillow", "枕头"),
        ("wardrobe", "衣柜"),
        ("bookcase", "书架"),
        ("cup", "杯子"),
        ("mug", "马克杯"),
        ("bottle", "瓶子"),
        ("plate", "盘子"),
        ("spoon", "勺子"),
        ("fork", "叉子"),
        ("knife", "刀"),
        ("bowl", "碗"),
        ("backpack", "背包"),
        ("umbrella", "雨伞"),
        ("wallet", "钱包"),
        ("purse", "手提包"),
        ("shoe", "鞋"),
        ("sandal", "凉鞋"),
        ("hat", "帽子"),
        ("helmet", "头盔"),
        ("sunglasses", "太阳镜"),
        ("guitar", "吉他"),
        ("piano", "钢琴"),
        ("drum", "鼓"),
        ("violin", "小提琴"),
        ("flute", "长笛"),
        ("trumpet", "小号"),
        ("ball", "球"),
        ("racket", "球拍"),
        ("ski", "滑雪板"),
        ("mask", "面具"),
        ("envelope", "信封"),
        ("book", "书"),
        ("newspaper", "报纸"),
        ("flower", "花"),
        ("tree", "树"),
        ("cabbage", "卷心菜"),
        ("broccoli", "西兰花"),
        ("corn", "玉米"),
        ("pumpkin", "南瓜"),
        ("apple", "苹果"),
        ("grape", "葡萄"),
        ("fig", "无花果"),
        ("bread", "面包"),
        ("cake", "蛋糕"),
        ("chocolate", "巧克力"),
        ("wine", "葡萄酒"),
        ("coffee", "咖啡")
    ]
}
